output: mythx.json
format: json

analyze:
    mode: quick
    create-group: true
    group-name: My fancy analysis
    solc: 0.5.16
    contracts:
        - PredictTheBlockHashChallenge
        - GuessTheRandomNumberChallenge