services: 
  - name: geth
    image: "ethereum/client-go:alltools-latest"
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: >
        mkdir -p /geth/keystore;
        cp /accounts/keystore/* /geth/keystore;
        cp /accounts/static-nodes.json /geth/;
        geth --nousb --datadir /geth/ init /accounts/genesis.json;
        geth --networkid 7777 --datadir /geth/ --http --http.addr 0.0.0.0 --miner.gasprice=${MINER_GASPRICE} --http.api "admin,web3,eth,net,personal,miner,txpool" --http.corsdomain "0.0.0.0" --txpool.nolocals --http.vhosts=* --verbosity=5 --port 30303 --nousb --miner.etherbase $(cat /accounts/address${INDEX}) --unlock $(cat /accounts/address${INDEX}) --allow-insecure-unlock --password /geth/pw.txt --mine --miner.threads=${MINER_THREADS} --nodekeyhex $(cat /accounts/priv$INDEX) --ethstats $NAME:${ETH_STATS_SECRET}@${ETHSTATS_SERVICE0_COMMON_NETWORK}:3000 --nodiscover
  #--bootnodes enode://$(cat /accounts/nodekey0)@${GETH_SERVICE0_COMMON_NETWORK}:30303?discport=30303
    environment:
      ETH_STATS_SECRET: testnet_secret
      MINER_GASPRICE: "1"
      MINER_THREADS: "1"
    input-files: 
      - source-path: ./genesis.json
        destination-path: /geth/genesis.json
      - source-path: password.txt
        destination-path: /geth/pw.txt
    resources:
      cpus: 6
      memory: 6 GB
      storage: 30 GiB
  
  - name: ethstats
    image: gcr.io/whiteblock/ethstats:master
    environment:
      HOST: "0.0.0.0"
    input-files:
      - source-path: ws_secret.json
        destination-path: /eth-netstats/ws_secret.json
  
  - name: record
    image: gcr.io/whiteblock/helpers/ethereum/record:master
    script:
      inline:
        app --target http://$GETH_SERVICE0_COMMON_NETWORK:8545
    resources:
      cpus: 1
      memory: 1 GiB
      storage: 10 GiB

  - name: tps-logger
    image: gcr.io/whiteblock/helpers/ethereum/tps-logger:master
    script:
      inline: tps-logger --node $GETH_SERVICE0_COMMON_NETWORK:8545 --record $RECORD_SERVICE0_COMMON_NETWORK:8080 --listen 0.0.0.0:7777
    resources:
      memory: 1 GiB

sidecars:
  - name: background-transactions
    sidecar-to:
      - geth
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    image: gcr.io/whiteblock/helpers/ethereum/tx:master
    script:
      inline: tx --chain-id ${CHAIN_ID} --tps ${TPS} --target $SERVICE:8545 --private-key-file /accounts/accounts.json --gas-limit ${GAS_LIMIT}
    environment:
      CHAIN_ID: "7777"
      TPS: "80"
      GAS_LIMIT: "4000000"
    resources:
      cpus: 2
      memory: 3 GB
      storage: 30 GiB

task-runners:
  - name: generate-accounts
    image: "gcr.io/whiteblock/helpers/ethereum/accounts:master"
    environment:
      ACCOUNTS: 20
    script:
      inline: accounts generate -c $ACCOUNTS -e -d /accounts
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    resources:
      cpus: 1
      memory: 2 GB

  - name: generate-genesis
    image: gcr.io/whiteblock/helpers/ethereum/genesis:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script:
      inline: genesis generate -a /accounts/accounts.json -o consensus=ethhash | tee /accounts/genesis.json
    resources:
      cpus: 1
      memory: 2 GB
  - name: generate-static-peers
    image: gcr.io/whiteblock/helpers/ethereum/static-peers:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    script: 
      inline: generate --accounts-file /accounts/accounts.json --network common-network --service geth | tee /accounts/static-nodes.json
  - name: generate-keystore
    image: gcr.io/whiteblock/helpers/geth/keystore:master
    volumes:
      - path: /accounts/
        name: accounts
        scope: singleton
    input-files: 
      - source-path: password.txt
        destination-path: /geth/pw.txt
    script:
      inline: keystore -p /geth/pw.txt -f /accounts/accounts.json -o /accounts/keystore/
    resources:
      cpus: 1
      memory: 2 GB

  - name: await-block-production
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545
    resources:
      memory: 1 GB

  - name: await-blocks-100
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545 --block 100
    resources:
      memory: 1 GB

  - name: await-blocks-200
    image: gcr.io/whiteblock/helpers/ethereum/await-blocks:master
    script:
      inline: await --target $GETH_SERVICE0_COMMON_NETWORK:8545 --block 200
    resources:
      memory: 1 GB

tests: 
  - name: geth_demo
    phases:
      - name: accounts
        tasks: 
        - type: generate-accounts
        system:
          - type: ethstats
            resources:
              networks:
                - name: common-network
            port-mappings:
            - "3000:3000"
      - name: keystore-genesis
        tasks:
          - type: generate-genesis
          - type: generate-keystore
          - type: generate-static-peers
      - name: start
        system:
          - type: geth
            count: 7
            resources:
              networks:
                - name: common-network
      - name: await-block-production
        duration: 5m
      #   tasks:
      #     - type: await-block-production
      #       timeout: 5m
      #       networks:
      #         - name: common-network
      - name: stats
        system:
        - type: record
          port-mappings:
            - "8080:8080"
          resources:
            networks:
              - name: common-network
      - name: start-tps-logger
        system:
        - type: tps-logger 
          port-mappings:
            - "7777:7777"
          resources:
            networks:
              - name: common-network
      - name: wait-for-blocks-100
        duration: 5m

      #   tasks:
      #     - type: await-blocks-100
      #       timeout: 60m
      - name: network-impairments
        system:
        - type: geth
          count: 7
          resources:
            networks:
              - name: common-network
                latency: 300ms
      - name: wait-for-blocks-200
        duration: 5m
      #   tasks:
      #     - type: await-blocks-100
      #       timeout: 60m
#
# Show account